# contimech : tools and functions useful in Continuum Mechanics

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
from simmit import smartplus as sim
import os

## tr(vec)

Provides the trace of a second order tensor written as a vector v in the SMART+ formalism. Return a double. Example:

In [2]:
v = np.random.rand(6)
trace = sim.tr(v)
print v
print trace

[ 0.50424105  0.94972348  0.9643845   0.79954931  0.27782655  0.98372605]
2.41834903318


## dev(vec)
  
Provides the deviatoric part of a second order tensor written as a vector v in the SMART+ formalism. Return a vec. Example: 

In [3]:
v = np.random.rand(6)
v_dev = sim.dev(v)
print v
print v_dev

[ 0.90437124  0.69797433  0.2711766   0.70762105  0.97792633  0.33721511]
[ 0.27986385  0.07346694 -0.35333079  0.70762105  0.97792633  0.33721511]


## Mises_stress(vec)

Provides the Von Mises stress $\sigma^{Mises}$ of a second order stress tensor written as a vector v in the SMART+ formalism. Return a double. 

In [4]:
v = np.random.rand(6)
Mises_sig = sim.Mises_stress(v)
print v
print Mises_sig

[ 0.45006445  0.45214929  0.42454694  0.30577849  0.8169376   0.14676202]
1.53231477222


## Mises_strain(vec)
Provides the Von Mises strain $\varepsilon^{Mises}$ of a second order stress tensor written as a vector v in the SMART+ formalism. Return a double. 

In [5]:
v = np.random.rand(6)
Mises_eps = sim.Mises_strain(v)
print v
print Mises_eps

[ 0.14339767  0.63494515  0.84302872  0.99943675  0.29472903  0.61356514]
0.812089634277


## eta_stress(vec)
Provides the stress flow:
    
$$\eta_{stress}=\frac{3/2\sigma_{dev}}{\sigma_{Mises}}$$

from a second order stress tensor written as a vector v in the SMART+ formalism (i.e. the shear terms are multiplied by 2, providing shear angles). Return a vec. 
  

In [6]:
v = np.random.rand(6)
sigma_f = sim.eta_stress(v)
print v
print sigma_f

[ 0.85109342  0.54556831  0.62364928  0.72843676  0.10464335  0.00396312]
[ 0.20436366 -0.14709131 -0.05727235  1.67588659  0.24074895  0.0091178 ]


## eta_strain(vec)
Provides the strain flow 

$$\eta_{strain}=\frac{2/3\varepsilon_{dev}}{\varepsilon_{Mises}}$$

from a second order strain tensor written as a vector v in the SMART+ formalism (i.e. the shear terms are multiplied by 2, providing shear angles). Return a vec. 

In [7]:
v = np.random.rand(6)
eps_f = sim.eta_strain(v)
print v
print eps_f

[ 0.09574442  0.81844191  0.30311511  0.86643954  0.32036989  0.6841309 ]
[-0.26141367  0.34797069 -0.08655703  0.73058881  0.27013848  0.57686469]


## v2t_stress(vec)
Converts a second order stress tensor written as a vector v in the SMART+ formalism into a second order stress tensor written as a matrix m. Return a mat. 

In [8]:
v = np.random.rand(6)
m = sim.v2t_stress(v);
print v
print m

[ 0.20388968  0.8602739   0.43087816  0.38692008  0.9734405   0.94324457]
[[ 0.20388968  0.38692008  0.9734405 ]
 [ 0.38692008  0.8602739   0.94324457]
 [ 0.9734405   0.94324457  0.43087816]]


## t2v_stress(vec)
Converts a second order stress tensor written as a matrix m in the SMART+ formalism into a second order stress tensor written as a vector v. Return a vec. 

In [9]:
m = np.random.rand(3,3)
m_symm = (m + m.T)/2
v = sim.t2v_stress(m_symm);
print m_symm
print v

[[ 0.21305822  0.41832992  0.60118161]
 [ 0.41832992  0.85758129  0.26746683]
 [ 0.60118161  0.26746683  0.89601423]]
[ 0.21305822  0.85758129  0.89601423  0.41832992  0.60118161  0.26746683]


## v2t_strain(vec)
Converts a second order strain tensor written as a vector v in the SMART+ formalism into a second order strain tensor written as a matrix m. Return a mat. 

In [10]:
v = np.random.rand(6)
m = sim.v2t_strain(v);
print v
print m

[ 0.66060514  0.5493198   0.12385499  0.78964374  0.78583183  0.3187543 ]
[[ 0.66060514  0.39482187  0.39291591]
 [ 0.39482187  0.5493198   0.15937715]
 [ 0.39291591  0.15937715  0.12385499]]


## t2v_strain(vec)

Converts a second order strain tensor written as a matrix m in the SMART+ formalism into a second order strain tensor written as a vector v. Return a vec. 

In [11]:
m = np.random.rand(3,3)
m_symm = (m + m.T)/2
v = sim.t2v_strain(m_symm);
print m_symm
print v

[[ 0.86092754  0.15230484  0.63427964]
 [ 0.15230484  0.37029279  0.71479089]
 [ 0.63427964  0.71479089  0.3609774 ]]
[ 0.86092754  0.37029279  0.3609774   0.30460968  1.26855929  1.42958177]


## J2_stress(vec)

Provides the second invariant of a second order stress tensor written as a vector v in the SMART+ formalism. Return a double. 

$$ J_2 (\boldsymbol{\sigma}) = \frac{1}{2} \sigma_{ij} \sigma_{ij} $$

In [12]:
v = np.random.rand(6)
J2 = sim.J2_stress(v)
print v
print J2

[ 0.47948547  0.11648965  0.15540006  0.87070977  0.8978231   0.94260142]
2.49243780525


## J2_strain(vec)
Provides the second invariant of a second order strain tensor written as a vector v in the SMART+ formalism. Return a vec. 

$$ J_2 (\boldsymbol{\varepsilon}) = \frac{1}{2} \varepsilon_{ij} \varepsilon_{ij} $$

In [13]:
v = np.random.rand(6)
J2 = sim.J2_strain(v)
print v
print J2

[ 0.84619915  0.90714003  0.00968792  0.34789138  0.31604571  0.13443645]
0.311227468978


## J3_stress(vec)
Provides the third invariant of a second order stress tensor written as a vector v in the SMART+ formalism. Return a double. 

$$ J_3 (\boldsymbol{\sigma}) = \frac{1}{2} \sigma_{ij} \sigma_{jk} \sigma_{ki} $$

In [14]:
v = np.random.rand(6)
J3 = sim.J3_stress(v)
print v
print J3

[ 0.85667831  0.43643232  0.99738465  0.46799781  0.7950665   0.91710972]
0.752515292143


## J3_strain(vec)
Provides the third invariant of a second order strain tensor written as a vector v in the SMART+ formalism. Return a vec. 

$$ J_3 (\boldsymbol{\varepsilon}) = \frac{1}{2} \varepsilon_{ij} \varepsilon_{jk} \varepsilon_{ki} $$


In [15]:
v = np.random.rand(6)
J3 = sim.J3_strain(v)
print v
print J3

[ 0.47697657  0.74346495  0.30771762  0.94938295  0.82129204  0.25953858]
0.0586373502057
